name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Lint
        if: ${{ github.event_name == 'push' }}
        run: npm run lint:ci --if-present
      - name: Test
        if: ${{ github.event_name == 'push' }}
        run: npm run test --if-present
      - name: Build
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run build --if-present
